development:
  clients:
    default:
      hosts:
        - <%= ENV['DB_HOST'] %>
      # Define the default database name.
      database: alicebot
      # Since this database points at a session connected to MongoHQ, we must
      # provide the authentication details.
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_PASS'] %>
      #database: alice_dev
      # hosts:
      #   - localhost:27017

test:
  clients:
    default:
      database: alice_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      hosts:
        - <%= ENV['DB_HOST'] %>
      # Define the default database name.
      database: alicebot
      # Since this database points at a session connected to MongoHQ, we must
      # provide the authentication details.
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_PASS'] %>
      #database: alice_dev
      # hosts:
      #   - localhost:27017
  # options:
  #   allow_dynamic_fields: false
  #   identity_map_enabled: true
  #   include_root_in_json: true
  #   include_type_for_serialization: true
  #   scope_overwrite_exception: true
  #   raise_not_found_error: false
  #   skip_version_check: false
  #   use_activesupport_time_zone: false
  #   use_utc: true
